version: "3.8"

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
